title: Josiah Cowan Project Portfolio
description: To showcase my knowledge to a future employer
[Linkedin](https://www.linkedin.com/in/josiah-cowan/)  || josiahcowan@gmail.com
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
